[tool.pytest.ini_options]
minversion = "7.0"
python_files = [
    "test_*.py"
]

[tool.mypy]
check_untyped_defs = true

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 200
extend-ignore = "E203,W503,SIM115"
per-file-ignores = "__init__.py:F401"
